### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by PhilipSargent**
Corrected Mcf definition
Added lots more units

### CODE REVIEW

**Comment by tamc** [comment]
Thanks Philip

Would you mind creating a new pull request against the tamc/gh-pages branch rather than the tamc/master branch?

That will make it easier for me to see what is new.

Thanks!

Tom

PS I will delete the master branch to avoid further confusion

**Comment by PhilipSargent** [comment]
oops sorry.
I really haven’t got my head around this yet.

**Comment by PhilipSargent** [comment]
Done (I hope)
The diff algorithm is broken it seems – I only changed or added a few lines, not all of them.

**Comment by tamc** [comment]
Thanks Philip

The reason for the diff showing too many changes was a change in line endings. Do you use Windows?

Anyway, if you pull the latest version, git should now handle different line endings and normalise them when committed.

Best wishes

Tom

**Comment by PhilipSargent** [comment]
Ah of course. My fault for trusting Excel to Do The Right Thing.
Next time, I will check for \n and I will run it through a dos2unix filter first if it was like that before.

But it’s in \r\n format now – sorry.

I do need to fix Tcf I see.

**Comment by tamc** [comment]
Super. It doesn’t cause any problems in use I don’t think, just in dif-fing.

**Pull request closed without merging**
